const mysteryCases = [
{title:"The Missing Museum Key",category:"city",ages:"9+",levels:["A1","A2"],focus:["Listening","Grammar","Logic & inference"],grammar:"Past Simple, prepositions",audio:"Security guard interview",goal:"Выяснить, кто последним видел ключ и где он оказался.",clues:["timeline","contradiction","location"],recommended:["Audio Timeline","Catch the Contradiction","Suspect Elimination","Final Verdict"]},
{title:"The Vanished School Mascot",category:"school",ages:"7+",levels:["A0 / Pre-A1","A1","A2"],focus:["Vocabulary","Speaking"],grammar:"have got, can, descriptions",audio:"Students talking after class",goal:"Найти школьный талисман по описаниям свидетелей.",clues:["description","object","location"],recommended:["Who Saw What?","Evidence Labels","Listen & Point","Detective Conference"]},
{title:"The Lost Airport Suitcase",category:"travel",ages:"9+",levels:["A1","A2","B1"],focus:["Listening","Vocabulary"],grammar:"questions, possessives",audio:"Airport lost-property conversation",goal:"Определить владельца перепутанного чемодана.",clues:["object","identity","detail"],recommended:["Listening Grid","Match Evidence to Suspect","Question the Witness","Case Report"]},
{title:"The Secret Library Note",category:"school",ages:"8+",levels:["A1","A2"],focus:["Reading","Vocabulary"],grammar:"imperatives, prepositions",audio:"Librarian voice message",goal:"Расшифровать записку и понять, кто её оставил.",clues:["code","word","location"],recommended:["Vocabulary Code","Hidden Detail","Evidence Hunt","Final Verdict"]},
{title:"The Missing Sports Trophy",category:"school",ages:"9+",levels:["A1","A2","B1"],focus:["Grammar","Logic & inference"],grammar:"Past Simple, time expressions",audio:"Coach interviews three students",goal:"Восстановить вечер и найти несостыковку в алиби.",clues:["timeline","alibi","contradiction"],recommended:["Grammar Alibi","Audio Timeline","Alibi Matrix","Catch the Contradiction"]},
{title:"The Strange Voice Message",category:"digital",ages:"11+",levels:["A2","B1","B2"],focus:["Listening","Logic & inference"],grammar:"modals of deduction",audio:"Anonymous voice message",goal:"Определить автора сообщения по языковым и контекстным деталям.",clues:["voice","inference","identity"],recommended:["Speaker Profile","What Must Have Happened?","Evidence Ranking","One-Minute Theory"]},
{title:"The Hotel Room Mix-Up",category:"travel",ages:"10+",levels:["A1","A2","B1"],focus:["Speaking","Listening"],grammar:"there is/are, requests",audio:"Hotel reception phone call",goal:"Понять, кто получил неправильный ключ и почему.",clues:["room","detail","sequence"],recommended:["Listening Grid","Reception Role-play","Sequence Repair","Final Explanation"]},
{title:"The Café Recipe Mystery",category:"city",ages:"8+",levels:["A1","A2"],focus:["Vocabulary","Reading"],grammar:"countables, quantities",audio:"Chef and waiter conversation",goal:"Найти пропавший рецепт и выявить неверную деталь заказа.",clues:["food","quantity","object"],recommended:["Evidence Labels","Odd Detail Out","Menu Evidence","Vocabulary Detective"]},
{title:"The Wrong Train Passenger",category:"travel",ages:"11+",levels:["A2","B1"],focus:["Listening","Speaking"],grammar:"Past Continuous, questions",audio:"Conductor questioning passengers",goal:"Понять, кто оказался не в том вагоне и как это связано с уликой.",clues:["movement","timeline","identity"],recommended:["Journey Timeline","Interrogate the Passenger","Who Was Where?","Detective Conference"]},
{title:"The Gallery Picture Swap",category:"city",ages:"12+",levels:["A2","B1","B2"],focus:["Reading","Logic & inference"],grammar:"passive voice, descriptions",audio:"Curator incident briefing",goal:"Определить, когда картину подменили и какая деталь это доказывает.",clues:["visual","sequence","document"],recommended:["Document Comparison","Evidence Ranking","Passive Reconstruction","Final Accusation"]},
{title:"The Missing Birthday Present",category:"mystery",ages:"7+",levels:["A0 / Pre-A1","A1"],focus:["Vocabulary","Listening"],grammar:"possessives, prepositions",audio:"Family members talking",goal:"Найти подарок по простым описаниям мест и предметов.",clues:["location","object","description"],recommended:["Listen & Point","Where Was It?","Picture Evidence","Mini Verdict"]},
{title:"The Mystery of the Closed Classroom",category:"school",ages:"10+",levels:["A1","A2"],focus:["Grammar","Reading"],grammar:"must/mustn't, can/can't",audio:"Teacher and caretaker dialogue",goal:"Понять, как кто-то попал в закрытый кабинет.",clues:["rule","access","time"],recommended:["Possible / Impossible","Rule Evidence","Question the Caretaker","Final Verdict"]},
{title:"The Broken Exhibition Robot",category:"digital",ages:"10+",levels:["A2","B1"],focus:["Listening","Vocabulary"],grammar:"Past Simple, cause/effect",audio:"Tech fair incident report",goal:"Определить, что произошло с роботом и какая команда была введена.",clues:["command","cause","sequence"],recommended:["Cause & Effect Chain","Command Reconstruction","Audio Timeline","Technical Witness"]},
{title:"The Secret Delivery",category:"city",ages:"11+",levels:["A2","B1"],focus:["Reading","Speaking"],grammar:"future forms, requests",audio:"Courier support call",goal:"Выяснить, кому предназначалась загадочная посылка.",clues:["address","identity","message"],recommended:["Address Clue Hunt","Customer Support Role-play","Message Comparison","Final Explanation"]},
{title:"The Missing Pet Poster",category:"city",ages:"7+",levels:["A0 / Pre-A1","A1","A2"],focus:["Reading","Vocabulary"],grammar:"has got, adjectives",audio:"Neighbour interview",goal:"Найти питомца по объявлениям и свидетельским описаниям.",clues:["description","location","time"],recommended:["Description Match","Map Clue","Who Said It?","Pet Search Report"]},
{title:"The Mystery Photo",category:"digital",ages:"10+",levels:["A1","A2","B1"],focus:["Speaking","Logic & inference"],grammar:"present continuous, might/must",audio:"Friends discussing a photo",goal:"Определить, где и когда сделана неизвестная фотография.",clues:["visual","weather","location"],recommended:["Photo Detective","Evidence Ranking","Modal Deduction","Convince the Team"]},
{title:"The School Radio Mix-Up",category:"school",ages:"9+",levels:["A1","A2"],focus:["Listening","Speaking"],grammar:"dates, times, future plans",audio:"School radio announcements",goal:"Найти ошибку, из-за которой все пришли не в то время.",clues:["time","announcement","comparison"],recommended:["Announcement Grid","What Changed?","Schedule Repair","Radio Correction"]},
{title:"The Forgotten Online Password",category:"digital",ages:"12+",levels:["A2","B1"],focus:["Reading","Logic & inference"],grammar:"conditionals, relative clauses",audio:"Support chat read aloud",goal:"Восстановить пароль по безопасным словесным подсказкам, не используя реальные данные.",clues:["code","word","inference"],recommended:["Clue Context","Conditional Puzzle","Code Builder","Final Solution"]},
{title:"The Mystery Restaurant Booking",category:"city",ages:"11+",levels:["A2","B1"],focus:["Listening","Grammar"],grammar:"reported speech, names and times",audio:"Restaurant phone logs",goal:"Понять, почему две компании получили одну бронь.",clues:["name","time","reported"],recommended:["Reported Statement","Booking Timeline","Compare Two Calls","Manager Brief"]},
{title:"The Secret Postcard",category:"travel",ages:"9+",levels:["A1","A2","B1"],focus:["Reading","Writing"],grammar:"past tense, place descriptions",audio:"Short travel diary",goal:"Определить город, откуда была отправлена открытка.",clues:["place","culture","detail"],recommended:["Travel Clue Hunt","Read Between the Lines","City Deduction","Write the Reply"]},
{title:"The Fake Event Poster",category:"digital",ages:"12+",levels:["A2","B1","B2"],focus:["Reading","Vocabulary"],grammar:"comparatives, dates, formal language",audio:"Organizer interview",goal:"Определить, какая афиша содержит ложную информацию.",clues:["document","comparison","date"],recommended:["Document Authenticity","Compare Details","Formal Language Detective","Evidence Ranking"]},
{title:"The Missing USB Drive",category:"digital",ages:"13+",levels:["B1","B2"],focus:["Listening","Speaking"],grammar:"reported speech, modals",audio:"Office team interview",goal:"Определить, кто последним пользовался флешкой и где она могла остаться.",clues:["device","timeline","statement"],recommended:["Statement Comparison","Office Alibi","Interrogate the Team","Evidence Board"]},
{title:"The Theatre Costume Switch",category:"city",ages:"9+",levels:["A1","A2"],focus:["Vocabulary","Speaking"],grammar:"clothes, adjectives, past simple",audio:"Backstage conversation",goal:"Понять, кто перепутал костюмы перед спектаклем.",clues:["clothes","description","sequence"],recommended:["Costume Match","Backstage Timeline","Witness Hot Seat","Final Explanation"]},
{title:"The Tourist Map Puzzle",category:"travel",ages:"8+",levels:["A1","A2"],focus:["Listening","Vocabulary"],grammar:"directions, prepositions",audio:"Tour guide directions",goal:"Пройти по маршруту и найти место, где спрятана улика.",clues:["map","direction","location"],recommended:["Listen & Mark the Map","Route Repair","Direction Code","Find the Final Location"]},
{title:"The Mystery Shopping Order",category:"digital",ages:"10+",levels:["A1","A2","B1"],focus:["Reading","Grammar"],grammar:"quantities, comparatives",audio:"Customer service call",goal:"Найти, где в заказе произошла ошибка.",clues:["quantity","product","document"],recommended:["Order Comparison","Quantity Detective","Customer Complaint","Error Chain"]},
{title:"The Secret Office Visitor",category:"city",ages:"14+",levels:["B1","B2"],focus:["Listening","Logic & inference"],grammar:"modals of deduction, past tenses",audio:"Reception and staff statements",goal:"Установить личность неизвестного посетителя по косвенным уликам.",clues:["identity","inference","statement"],recommended:["Visitor Profile","Modal Deduction","Contradiction Hunt","Evidence Ranking"]},
{title:"The Missing Festival Ticket",category:"city",ages:"10+",levels:["A1","A2"],focus:["Listening","Reading"],grammar:"past simple, numbers",audio:"Friends retracing their day",goal:"Восстановить маршрут и найти, где потерялся билет.",clues:["timeline","location","object"],recommended:["Timeline Cards","Map Clue","Receipt Evidence","Final Location"]},
{title:"The Wrong Flight Announcement",category:"travel",ages:"11+",levels:["A2","B1"],focus:["Listening","Logic & inference"],grammar:"numbers, times, conditionals",audio:"Airport announcements",goal:"Понять, какое сообщение было ошибочным и что изменилось.",clues:["announcement","time","comparison"],recommended:["What Changed?","Announcement Grid","Possible / Impossible","Passenger Advice"]},
{title:"The Mysterious Diary Page",category:"mystery",ages:"12+",levels:["A2","B1","B2"],focus:["Reading","Writing"],grammar:"past tenses, narrative language",audio:"Diary entry recording",goal:"Восстановить пропущенный эпизод по косвенным деталям.",clues:["narrative","sequence","emotion"],recommended:["Missing Piece","Narrative Timeline","Read Between the Lines","Write the Missing Entry"]},
{title:"Who Left the Note?",category:"mystery",ages:"8+",levels:["A1","A2","B1"],focus:["Reading","Logic & inference"],grammar:"questions, descriptions",audio:"Three short witness statements",goal:"Сопоставить почерк/лексику/факты и определить автора записки.",clues:["word","identity","contradiction"],recommended:["Language Fingerprint","Statement Comparison","Suspect Elimination","Final Verdict"]}
];

const evidenceTypes = [
{title:"Interrogation",desc:"допрос или уточняющий разговор с подозреваемым"},{title:"Witness statement",desc:"последовательный рассказ свидетеля"},{title:"Voice message",desc:"короткое сообщение с естественной речью"},{title:"Phone call",desc:"диалог с пропусками и контекстными подсказками"},{title:"Detective briefing",desc:"вводная по делу и известные факты"},{title:"News report",desc:"нейтральное сообщение о событии"},{title:"Overheard conversation",desc:"разговор, который ученики как будто случайно слышат"},{title:"Announcement",desc:"школьное, аэропортовое или городское объявление"},{title:"Email / chat",desc:"письменная улика для чтения"},{title:"Receipt / ticket",desc:"документ с числами, временем и деталями"},{title:"Map / timetable",desc:"визуальная логическая улика"},{title:"Photo description",desc:"текстовое описание изображения или сцены"}
];

const taskGroups = {
"Listening":[
["Evidence Hunt","Найти в аудио конкретные факты, которые могут стать уликами.","evidence","6"],["Who Said It?","Соотнести реплики и персонажей.","input","6"],["True / False / Not Mentioned","Проверить точное понимание фактов и не додумывать отсутствующую информацию.","input","6"],["Listening Grid","Заполнить person / place / time / object / action.","input","5"],["Missing Detail","Восстановить пропущенную деталь показаний.","evidence","5"],["Listen & Order","Расположить события в порядке звучания.","input","6"],["First Listening: What Happened?","Определить общий смысл без охоты за деталями.","briefing","3"],["Second Listening: Find the Clue","Во втором прослушивании найти ключевые доказательства.","evidence","4"],["Suspicious Word","Определить слово или формулировку, которая делает реплику подозрительной.","inference","4"],["Statement Comparison","Сравнить две аудиоверсии одного события.","evidence","6"],["Catch the Contradiction","Найти противоречие между двумя фрагментами.","deduction","5"],["Audio Timeline","Восстановить последовательность событий по времени.","deduction","6"],["What Changed?","Сравнить две версии объявления или показаний.","evidence","5"],["Listen & Mark the Map","Отметить маршрут или места на карте.","evidence","6"],["Evidence Bingo","Отмечать услышанные детали в поле улик.","input","9"]],
"Vocabulary":[
["Detective Vocabulary Board","Распределить слова по Suspects / Actions / Places / Objects.","input","12"],["Clue Context","Определить значение слова по контексту улики.","input","6"],["Odd Detail Out","Найти слово или деталь, которая не вписывается в группу.","inference","6"],["Evidence Labels","Подписать предметы, места или документы ключевой лексикой.","input","8"],["Replace the Detective's Words","Заменить слишком общие слова более точной целевой лексикой.","practice","6"],["Vocabulary Code","Решить код, где ответы образуют слово-улику.","evidence","6"],["Collocation Evidence","Собрать естественные словосочетания из материалов дела.","practice","8"],["Describe the Evidence","Описать предмет-улику так, чтобы партнёр его определил.","production","4"],["Forbidden Word","Объяснить улику без использования главного слова.","production","5"],["Witness Vocabulary Upgrade","Сделать показания точнее и естественнее.","practice","6"],["Word Evidence Sort","Разделить полезные и отвлекающие слова.","deduction","10"],["Lexical Fingerprint","Сопоставить характерную лексику с персонажами.","deduction","6"],["Synonym Suspect","Выбрать эквивалент, который сохраняет смысл показаний.","practice","6"],["Picture-to-Clue Match","Соотнести изображения/описания и слова-улики.","input","8"],["Vocabulary Trail","Каждый правильный ответ открывает следующий шаг маршрута.","evidence","7"]],
"Grammar":[
["Grammar Alibi","Заполнить формы и получить готовый таймлайн алиби.","evidence","6"],["Question the Suspect","Построить вопросы для допроса из prompts.","production","6"],["Correct the Witness Statement","Исправить грамматические ошибки, меняющие смысл показаний.","practice","6"],["Grammar Evidence Gap","Вставить форму, необходимую для точной интерпретации улики.","practice","6"],["Choose the Meaning","Сопоставить форму и реальное значение в контексте дела.","input","5"],["Sentence Reconstruction","Собрать реплики из перемешанных элементов.","practice","6"],["Spot the Language Mistake","Найти грамматическую ошибку в показаниях.","practice","6"],["Change the Perspective","Пересказать событие от лица другого персонажа.","production","5"],["Reported Statement","Преобразовать прямую речь свидетеля в reported speech.","evidence","5"],["What Must Have Happened?","Использовать modals of deduction для версии событий.","deduction","5"],["Tense Timeline","Выбрать время по логике последовательности событий.","deduction","6"],["Conditional Consequence","Соединить условие и последствия для проверки версии.","deduction","5"],["Passive Case File","Переформулировать факты в passive voice для отчёта.","practice","5"],["Reference Detective","Определить, к кому/чему относятся pronouns и reference words.","input","6"],["Grammar Choice = Clue","Каждый грамматический выбор меняет смысл и ведёт к разным версиям.","evidence","5"]],
"Reading":[
["Read the Case File","Извлечь ключевые факты из краткого dossier.","briefing","5"],["Compare Two Messages","Найти совпадения и различия в двух сообщениях.","evidence","6"],["Hidden Detail","Найти маленькую деталь, которая меняет ход расследования.","evidence","5"],["Which Document Matters?","Определить, какой документ действительно связан с делом.","deduction","4"],["Read Between the Lines","Сделать вывод, который не сформулирован напрямую.","inference","5"],["Match Evidence to Suspect","Соотнести письменные улики и персонажей.","deduction","6"],["Document Authenticity","Определить подозрительную или поддельную версию документа.","deduction","5"],["Information Gap Files","У двух учеников разные фрагменты дела; нужно обменяться информацией.","production","6"],["Headline vs Reality","Сравнить краткий заголовок и фактические детали.","inference","5"],["Read and Eliminate","По каждому фрагменту исключать невозможные версии.","deduction","5"],["Receipt Evidence","Извлечь данные из чека, билета или заказа.","evidence","6"],["Message Thread Reconstruction","Восстановить порядок переписки.","deduction","7"],["Find the Unreliable Sentence","Определить предложение, которое не подтверждается источниками.","deduction","5"],["Map + Text Crosscheck","Сверить текстовые указания с картой.","evidence","6"],["Micro-Text Clue Chain","Несколько коротких текстов последовательно открывают новые данные.","evidence","5"]],
"Speaking":[
["Interrogate the Suspect","Ролевая игра: детектив задаёт вопросы, подозреваемый отвечает по карточке.","production","6"],["Defend Your Suspect","Защитить персонажа, используя доказательства.","production","3"],["Detective Conference","Команда обсуждает версии и выбирает следующую линию расследования.","deduction","4"],["Convince the Team","Убедить группу в своей версии с опорой на факты.","production","3"],["One-Minute Theory","Дать короткую цельную версию произошедшего.","production","1"],["Ask for an Alibi","Провести мини-интервью с обязательными вопросами.","production","6"],["Witness Hot Seat","Ученик в роли свидетеля отвечает на неожиданные вопросы группы.","production","6"],["Press Conference","Группа задаёт вопросы персонажу после нового открытия.","production","8"],["Evidence Auction","Команды спорят, какие улики наиболее ценны.","deduction","6"],["Agree on the Prime Suspect","Договориться о главной версии и обосновать её.","deduction","4"],["Reconstruct the Scene","Устно собрать последовательность события по фрагментам.","production","6"],["Detective vs Detective","Две версии расследования конкурируют по силе аргументов.","production","3"],["Information Gap Interview","Партнёры получают разные факты и заполняют пробелы вопросами.","production","6"],["Role-card Phone Call","Проиграть звонок по скрытым карточкам ролей.","production","1"],["Final Oral Verdict","Назвать решение и минимум 2–3 доказательства.","verdict","3"]],
"Writing":[
["Write the Final Report","Написать краткий итог расследования по структуре.","verdict","1"],["Complete the Case File","Заполнить краткие поля dossier после работы с источниками.","evidence","6"],["Witness Statement","Написать показание от лица персонажа.","production","1"],["Text Message Evidence","Создать сообщение, которое логично дополняет известные факты.","production","2"],["Detective Notes","Вести краткие записи: fact / clue / question.","evidence","6"],["Missing Object Report","Оформить объявление о пропавшем объекте/питомце.","production","1"],["Explain Your Theory","Объяснить свою гипотезу и доказательства.","deduction","1"],["Write Three Questions","Подготовить вопросы для следующего этапа допроса.","production","3"],["Alternative Ending","Создать альтернативное решение, не противоречащее данным.","production","1"],["Final Accusation","Написать короткое обвинение/вывод с evidence language.","verdict","1"],["Police-style Summary","Сжато пересказать факты нейтральным стилем.","production","1"],["Email to the Detective","Написать письмо с новой найденной уликой.","production","1"],["Correct the Record","Переписать неточную запись так, чтобы она соответствовала источникам.","evidence","5"],["Timeline Caption Writing","Подписать ключевые моменты расследования предложениями.","practice","6"],["Write the Missing Entry","Дополнить дневник/чат/логический фрагмент, опираясь на контекст.","production","1"]],
"Logic & inference":[
["Suspect Elimination","Последовательно исключать версии по конкретным уликам.","deduction","5"],["Alibi Matrix","Заполнить таблицу suspect × time × place × evidence.","deduction","6"],["Who Could Be There?","Определить, кто физически мог находиться в нужном месте.","deduction","5"],["Evidence Ranking","Расположить улики от слабой к наиболее убедительной.","deduction","6"],["Build the Timeline","Собрать общую последовательность событий из разных источников.","deduction","7"],["Contradiction Hunt","Найти несовместимые утверждения.","deduction","5"],["Motive — Evidence — Suspect","Соединить возможный мотив, доказательство и персонажа.","deduction","5"],["Irrelevant Clue","Определить улику-приманку, которая не влияет на решение.","deduction","5"],["Missing Piece","Понять, какой информации не хватает для уверенного вывода.","inference","4"],["Two Truths and a Lie: Witness","Определить неподтверждённое утверждение свидетеля.","deduction","3"],["Detective's Deduction","Сформулировать логический вывод из двух фактов.","deduction","5"],["Possible / Impossible","Классифицировать версии по доступным данным.","deduction","6"],["Know / Think / Need","Разделить факты, предположения и вопросы.","briefing","9"],["Evidence Chain","Построить цепочку факт → вывод → новая улика.","deduction","5"],["One Clue Changes Everything","После новой детали пересмотреть первоначальную версию.","deduction","4"]],
"Integrated":[
["Case Prediction","По названию/вводной предположить, что произошло.","briefing","3"],["Clue Unlock","Каждое выполненное языковое действие открывает новую улику.","evidence","5"],["Language Escape Path","Правильные ответы определяют следующий источник дела.","evidence","6"],["Evidence Board","После каждого этапа обновлять Facts / Suspects / Questions / Evidence.","evidence","4"],["Case Route Choice","Команда выбирает, кого слушать/читать дальше, и объясняет выбор.","deduction","3"],["Red Herring Check","Проверить подозрительную улику на реальную значимость.","deduction","4"],["Clue-to-Question Loop","Новая улика должна породить следующий вопрос расследования.","deduction","5"],["Progressive Suspect Cards","После этапов дополнять карточки персонажей новыми данными.","evidence","4"],["Evidence Passport","Для каждой улики отметить source / fact / meaning / reliability.","deduction","5"],["Mini Verdict Checkpoint","После середины дела дать предварительную версию и пересмотреть её позже.","deduction","2"],["Branching Interview","Ответ на языковую задачу определяет следующий вопрос свидетелю.","production","5"],["Cross-source Verification","Подтвердить один факт минимум двумя разными источниками.","deduction","5"],["Case File Puzzle","Финальная комбинация нескольких выполненных заданий даёт решение.","verdict","5"],["Teacher Pause Point","Встроенная точка для обсуждения стратегии, а не ответа.","briefing","1"],["Final Verdict + Evidence Standard","Решение принимается только при наличии минимум 2 независимых доказательств.","verdict","3"]]
};

const taskBank=[]; Object.entries(taskGroups).forEach(([skill,items])=>items.forEach((x,i)=>taskBank.push({id:skill.toLowerCase().replace(/[^a-z]+/g,'-')+'-'+i,title:x[0],description:x[1],skill,stage:x[2],defaultItems:x[3]})));
